defenseunicorns/uds-cli

- src/cmd/deprecated_bundle.go
- src/cmd/root.go
- src/cmd/uds.go
- src/test/e2e/bundle_test.go
- Adds create, deploy, etc cmds to the the root `uds` cmd
- Adds deprecation warnings for using `uds bundle ...` syntax
- Updates tests that use remotes to the uds `uds ...` syntax (attempting to test both syntaxes before deprecation without running every test twice)
> begins deprecation of 'bundle' syntax in CLI

- README.md
- src/pkg/bundle/create.go
- src/pkg/bundle/deploy.go
- src/types/bundle.go
- Cleans up verbiage during `confirm` messages
- Ensures users are `confirm`'ing bundle deployment, not Zarf pkg deployment
> cleans up confirm behavior on create and deploy

- src/cmd/deprecated_bundle.go
- src/cmd/internal.go
- src/cmd/root.go
- src/cmd/uds.go
- src/cmd/version.go
- src/cmd/viper.go
- src/config/config.go
- src/pkg/bundle/bundle.go
- src/pkg/bundle/publish.go
- src/pkg/bundle/pull.go
- src/pkg/bundle/remote.go
- src/pkg/bundle/tarball.go
- src/pkg/bundler/remote.go
- src/pkg/bundler/tarball.go
- src/pkg/utils/utils.go
- Restores OCI concurrency by refactoring "pull" and "publish" bundle ops to use `oras.Copy()`
- Edits imports to have goimports style syntax
> Restore OCI concurrency

- .github/workflows/test-schema.yaml
- hack/test-generate-schema.sh
- src/pkg/runner/runner.go
- src/test/tasks.yaml
- src/types/tasks.go
- tasks.schema.json
Removes `name` key under an `[]actions.task`, new syntax is:
```
actions:
- task: name-of-task
```
> flattens task yaml structure

- src/cmd/run.go
- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks.yaml
Fixes issue where runner cmds weren't being templated with vars
> fix: ensures runner cmds are templated

- src/cmd/run.go
- src/config/config.go
- src/config/lang/lang.go
- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks.yaml
Addresses #146 adding the --set option to set variables when calling `uds run`
> feat: add --set option for task runner variables

- src/cmd/root.go
- src/cmd/uds.go
- src/cmd/viper.go
- src/config/config.go
- src/pkg/bundle/bundle.go
- src/pkg/bundle/common.go
- src/pkg/bundle/remote.go
- src/pkg/bundle/tarball.go
- src/pkg/bundler/remote.go
- src/pkg/bundler/tarball.go
- src/pkg/cache/cache.go
- src/pkg/sources/remote.go
- src/pkg/utils/oci.go
- src/pkg/utils/utils.go
- Implements caching and OCI concurrency for pulling remote Zarf packages during bundle create and deploy operations
- Refactors some really common OCI logic into functions now in `utils/oci.go`
> feat: caching and OCI concurrency for remote packages during bundle create and deploy

- README.md
- docs/runner.md
Adds `docs/runner.md` for the UDS runner feature
> docs: uds runner

- src/cmd/uds.go
- src/config/lang/lang.go
The `uds publish` command's help message was printing the `uds pull` command's message. Added new verbiage for publish
n/a
> fix: add shorthand instructions for publish command

- src/pkg/bundle/bundle.go
- src/pkg/bundle/remote.go
Removes annotation from root manifest layers to fix broken pull. Other logic in the codebase depends on those annotations and adding an additional one jacked up that logic
> fix: hotfix for broken pull operation

- .github/workflows/scan-codeql.yaml
- .github/workflows/test-e2e.yaml
- .github/workflows/test-unit.yaml
- .goreleaser.yaml
When the release pipeline runs, don't put the Github Release in draft status, go ahead and release it automatically
> chore: remove draft status after releasing

- .gitignore
- src/cmd/run.go
- src/pkg/bundler/remote.go
- src/pkg/cache/cache.go
- src/pkg/runner/runner.go
- src/test/common.go
- src/test/tasks/even-more-tasks-to-import.yaml
- src/test/tasks/more-tasks-to-import.yaml
- src/test/tasks/tasks-to-import.yaml
- src/test/tasks/tasks.yaml
- src/types/tasks.go
- tasks.schema.json
Adds ability to import local task files into the runner using syntax:
```yaml
includes:
- foo: ./tasks-to-import.yaml
tasks:
- name: the-task
actions:
- task: foo:imported-task
```
Where `imported-task` exists in the `tasks-to-import.yaml`
> feat: import local tasks into runner

- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks.yaml
Addresses #193 uds run cannot rerun tasks in the same execution
> feat: allow running tasks multiple times in execution

- renovate.json
- src/test/bundles/04-init/uds-bundle.yaml
Renovate wasn't updating the proper files, tested locally with `RENOVATE_CONFIG_FILE=renovate.json npx renovate --token=<my_pat> --schedule="" --require-config=ignored --dry-run=full`
> chore: refines renovate configs to pick up Zarf updates

- renovate.json
- Had a chicken/egg scenario where the Zarf Golang dep depended on the Zarf version used in the test suite, which broke Renovate. This PR ensures that Zarf update PRs from Renovate combine Go mod update with the test suite update
> chore: ensures all Zarf deps get updated together

- src/pkg/bundle/deploy.go
- src/test/bundles/07-helm-overrides/uds-bundle.yaml
- src/test/e2e/bundle_test.go
Enables complex data types like objects and lists in bundle value overrides
Fixes #239
> feat: enables complex helm overrides in bundle values

- src/pkg/bundle/deploy.go
- src/pkg/bundle/remove.go
- src/test/e2e/bundle_test.go
Improves bundle remove logic, so it doesn't just die if attempting to remove a package that isn't deployed. Now it gives a warning and continues
Relates to #236
> chore: improve bundle remove logic

- README.md
- src/cmd/uds.go
- src/config/lang/lang.go
- src/pkg/bundle/common.go
- src/pkg/bundle/deploy.go
- src/pkg/bundle/remove.go
- src/test/e2e/bundle_test.go
- src/types/bundler.go
Enable the ability to resume bundle deploy. Ability to resume bundle remove, is already available with remove work that was previously done.
Relates to #61
> feat: enable bundle --resume

- src/pkg/sources/remote.go
Fixes an off-by-one error when validating package integrity
> fix: fixes off-by-one error when validating package integrity

- README.md
- src/pkg/bundle/deploy.go
- src/test/e2e/bundle_test.go
- src/test/packages/no-cluster/output-var/zarf.yaml
enables setting zarf vars with env vars
Fixes #252
> feat: enables setting zarf vars with env vars

- src/pkg/bundle/remote.go
- src/test/bundles/06-ghcr/uds-bundle.yaml
- src/test/e2e/bundle_test.go
update how we match packages when not providing the full path
Relates to #195
> chore: update delivery bundle path matching

- src/cmd/uds.go
- src/test/bundles/01-uds-bundle/uds-config.yaml
- src/test/e2e/bundle_test.go
- src/types/bundler.go
Switches to unmashal with goyaml + `omitempty` on `variables`.
Also added a sample uds-config that just uses options (no variables) on the 01 test to hopefully catch this in the future, can turn it into a separate test case if desired.
Fixes https://github.com/defenseunicorns/uds-cli/issues/276
> fix: properly parse config files missing `variables`

- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks.yaml
Issue was found where if you reference a task with multiple includes from another task, it errors out not being able to pull in those includes. Not able to process includes of "sibling"
Fixes #283
> fix: handle multiple nested includes

- src/cmd/root.go
- src/cmd/run.go
- src/config/config.go
- src/config/lang/lang.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks.yaml
Adds `uds run --list` flag to support listing tasks in a task file.
Fixes https://github.com/defenseunicorns/uds-cli/issues/172
> feat: add list flag for run

- src/pkg/bundle/common.go
- src/pkg/bundle/common_test.go
Fixes issue where bundle validation was not identifying the correct chart/component when multiple were present (due to the use of pointers). Break added to exit the loops when the match is found.
Fixes #
Relates to #
> fix: override validation with multiple components

- Makefile
- hack/push-test-artifacts.sh
- src/config/config.go
- src/pkg/bundle/bundle.go
- src/test/bundles/06-ghcr/uds-bundle.yaml
- src/test/e2e/commands_test.go
- src/test/e2e/ghcr_test.go
Fixes a bug where the bundle couldn't get pulled from GHCR due to using the wrong media type
> fix: fixes bad media type when using create -o with GHCR

- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks.yaml
Update runner to call `uds zarf tools wait-for` vs `uds tools wait-for` since zarf is now vendored in as part of uds-cli.
Fixes bug palassis found
> fix: task call to uds zarf tools wait-for

- Makefile
- docs/overrides.md
- src/pkg/bundle/remote.go
- src/pkg/bundle/tarball.go
- src/pkg/bundler/remote.go
- src/pkg/utils/oci.go
- src/test/bundles/09-uds-bundle-yml/uds-bundle.yml
- src/test/common.go
- src/test/e2e/bundle_test.go
- src/test/e2e/ghcr_test.go
- src/test/e2e/variable_test.go
- refactors instances of `desc.Annotations == nil` to have more specific checks; this will allow us to add annotations (not title!) to the root manifest of bundles
- adds test for plain `uds` cmd
- refactors SBOM logic and provides better warnings
- docs fix
> chore: refactor Annotations and SBOM logic

- src/config/config.go
- src/pkg/bundle/bundle.go
- src/pkg/bundle/common.go
- src/pkg/bundle/deploy.go
- src/pkg/bundle/provider.go
- src/pkg/bundle/remote.go
- src/pkg/bundle/remove.go
- src/pkg/bundle/tarball.go
- src/test/bundles/10-package-naming/uds-bundle.yaml
- src/test/e2e/bundle_test.go
Allows you to use custom names when referencing a remote zarf package in your uds-bundle.yaml. This does not apply when referencing local zarf packages. When referencing local zarf packages, the bundle package name must still match the actual zarf package name
Relates to #306
> feat: allow custom zarf package names for remote package refs

- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks-to-import.yaml
- src/test/tasks/tasks.yaml
Task runner infinite loops possible when task files include each other
Fixes #351
> fix: includes task loops

- src/pkg/bundle/deploy.go
- src/test/bundles/07-helm-overrides/uds-config.yaml
- src/test/e2e/variable_test.go
Fixes error passing variable where value is a string of comma separated values to helm chart
Fixes #348
> fix: allow comma separated string values for helm overrides

- README.md
- src/pkg/bundle/deploy.go
- src/test/e2e/variable_test.go
- src/test/packages/no-cluster/output-var/zarf.yaml
- src/test/packages/no-cluster/receive-var/zarf.yaml
This PR allows you to set package specific variables on deploy
Relates to #364
> feat: set flag for specific package vars

- Makefile
- docs/runner.md
- src/cmd/run.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks-no-default.yaml
- src/test/tasks/tasks.yaml
add default task behavior to uds run per [this issue](https://github.com/defenseunicorns/uds-cli/issues/316).
...
Fixes #
[316](https://github.com/defenseunicorns/uds-cli/issues/316)
Relates to #
- [ x] New feature (non-breaking change which adds functionality)
> feat: add default task behavior to uds run

- README.md
- src/pkg/bundler/tarball.go
- src/test/bundles/04-init/uds-bundle.yaml
- src/types/bundle.go
- uds.schema.json
Swap `optional-components` to `optionalComponents`. Ensure we are only using camelCase in the `uds-bundle.yaml`
> chore: only use camelCase in yaml

- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks.yaml
False task loop detected when referencing multiple tasks from the same include in an actions
Fixes #391
> fix: false positive task loop

- src/pkg/bundle/remote.go
Fixes bug that prevented a UDS Bundle from deploying without a cluster
Fixes https://github.com/defenseunicorns/uds-cli/issues/397
> fix: don't error out when a cluster isn't available

- .gitignore
ignore new hidden folder used to store release assets downloaded using the gh cli inside a local repo. This is just a convenience for devs that use gh cli in this way.
> chore: ignore new hidden folder used to store release assets downloaded using the gh cli

- docs/runner.md
- src/pkg/runner/runner.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks.yaml
In a task file, if a default is not set for a variable, the UDS runner will now look to see if an environment variable (prefixed with `UDS_`) is set for that bundle variable and set that as the default.
Relates to #257 
- [ X Test, docs, adr added or updated as needed
> feat: task runner - grab defaults from env vars if not specified

- docs/runner.md
- src/cmd/run.go
- src/config/config.go
- src/pkg/runner/runner.go
- src/test/e2e/runner_inputs_test.go
- src/test/e2e/runner_test.go
- src/test/tasks/inputs/tasks.yaml
- src/test/tasks/tasks.yaml
The `--with` flag was meant to be used for testing tasks with `inputs` from the CLI. This feature ended up being confusing for users so we'd like to remove it. We believe this will encourage better testing patterns because it forces users to test their `inputs` with actual tasks instead of through the CLI.
Furthermore, we expanded the use of runner variables to ensure they can be passed into tasks using `with`
> feat: removes --with, expands variables for inputs

- .github/pull_request_template.md
- main.go
- src/test/e2e/zarf_test.go
This adds the zarf schema in the repo to the uds binary so that it can be used by Zarf during zarf dev lint.
Fixes #359
> fix: add support for zarf dev lint

- src/pkg/bundle/deploy.go
- src/test/bundles/07-helm-overrides/uds-bundle.yaml
Fixes bug when variables in overrides are not all upper case
Fixes #427
> fix: case sensitivity in override vars

- src/cmd/root.go
- src/test/e2e/variable_test.go
Adds z alias for running vendored in zarf
Relates to #419
> feat: alias vendored zarf to z

- src/pkg/bundle/common.go
- src/pkg/bundle/deploy.go
- src/pkg/bundler/fetcher/local.go
- src/pkg/sources/remote.go
- src/pkg/utils/sbom.go
- Fixes gosec lint issues for the pkg
Fixes #
Relates to #
> fix: gosec lint issues for the pkg

- .github/workflows/nightly-ghcr.yaml
- .github/workflows/test-e2e-pr.yaml
- Makefile
- src/test/e2e/bundle_test.go
- src/test/e2e/ghcr_test.go
- ensure PR workflows can't write to GHCR (thanks @bburky !)
- create nightly workflow for testing GHCR writes
> chore: ensure PR workflows can't write to GHCR

- src/cmd/root.go
- src/cmd/run.go
- src/cmd/uds.go
- src/pkg/bundler/bundler.go
- src/pkg/bundler/fetcher/fetcher.go
- src/pkg/bundler/fetcher/local.go
- src/pkg/bundler/fetcher/remote.go
- src/pkg/bundler/localbundle.go
- src/pkg/bundler/remotebundle.go
- src/pkg/utils/sbom.go
Addresses Github linter findings
> chore: addresses github linter findings

- src/pkg/bundle/common.go
- src/test/bundles/03-local-and-remote/uds-bundle.yaml
- src/test/bundles/04-init/uds-bundle.yaml
- src/test/bundles/05-gitrepo/uds-bundle.yaml
- src/test/bundles/07-helm-overrides/uds-bundle.yaml
- src/test/bundles/08-var-precedence/uds-bundle.yaml
- src/test/bundles/09-uds-bundle-yml/uds-bundle.yml
- src/test/bundles/11-real-simple/uds-bundle.yaml
- src/test/bundles/12-exported-pkg-vars/uds-bundle.yaml
fixes zarf package paths to be relative to the bundle directory vs the working directory
Fixes #
> fix: relative paths for bundle create

- README.md
Updates Zarf version in Quickstart section of README. Versions of Zarf <0.32.x are not compatible with UDS CLI
> fix: updates Zarf version in README

- .github/workflows/commitlint.yaml
```
Warn: script injection with untrusted input ' github.event.pull_request.title ': .github/workflows/commitlint.yml:28
```
- https://securityscorecards.dev/viewer/?uri=github.com/defenseunicorns/pepr
- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
...
Fixes #
Relates to #
> chore: fixed the dangerous workflow

- src/cmd/uds.go
- src/config/config.go
- src/pkg/bundle/provider.go
- src/pkg/bundle/pull.go
- src/pkg/bundle/remote.go
- src/pkg/bundle/tarball.go
- src/pkg/cache/cache.go
- src/test/e2e/bundle_test.go
- refactors pull operation and provider
Fixes #177
> chore: refactor pull operation

- src/pkg/bundle/common.go
Replace stack trace with proper err messaging when the remote can't be resolved in the case of:
- being disconnected
- not having a valid arch in the remote repo
Fixes #459
> fix: adds better err messaging when remote fails to resolve

- src/pkg/utils/oci.go
- fixes stack trace for bundles where len(bundleName) < "oci://"
Fixes #435
> fix: error when removing bundles with short names

- src/test/common.go
Our tests are flaky as the dickens (see error below), here's a simple test to see if the registry simply isn't ready
> fix: add a wait to the registry startup during tests

- src/pkg/bundle/remote.go
- src/test/e2e/bundle_test.go
- src/test/e2e/commands_test.go
Fixes bug where the bundle root manifest config was missing after pulls. This prevented publishing to other OCI repos
> fix: ensure manifest config is included with pulls

- go.mod
- go.sum
- src/cmd/root.go
- src/cmd/vendored.go
- src/config/lang/lang.go
- Fixes tab completion for `uds run`
- moves zarf and run commands to vendored.go
> fix: autocomplete and vendor refactor

- src/cmd/vendored.go
- src/test/e2e/runner_test.go
- src/test/tasks/tasks.yaml
UDS_ARCHITECTURE environment variable wasn't being picked up by the runner
Fixes #495
> fix: pass UDS_ARCHITECTURE to runner

- src/cmd/vendored.go
Fixes ->
Running uds zarf version returns 0.32.4
Running zarf version returns v0.32.4
this causes an issue when attempting to run uds zarf init it attempts to pull the package from oci://ghcr.io/defenseunicorns/packages/init:0.32.4 which is incorrect. It should be oci://ghcr.io/defenseunicorns/packages/init:v0.32.4
Fixes #517
> fix: vendored in zarf version tag

- .github/actions/save-logs/action.yaml
- .github/workflows/nightly-uds-core.yaml
- src/cmd/uds.go
- src/pkg/bundle/common.go
- src/pkg/bundle/tui/common.go
- src/pkg/bundle/tui/deploy/handlers.go
- src/pkg/bundle/tui/deploy/model.go
- src/pkg/bundle/tui/deploy/views.go
`uds deploy k3d-core-istio-dev:0.16.1` fails with a stack trace whenever a cluster isn't present. This PR nil checks the cluster object so the program doesn't blow up
> fix: err when deploying with BubbleTea with no cluster

- src/pkg/bundle/deploy.go
- src/pkg/bundle/tarball.go
- src/pkg/bundle/tui/deploy/model.go
- src/pkg/bundle/tui/deploy/model_test.go
- src/test/e2e/commands_test.go
- src/test/e2e/tui_test.go
> chore: adds TUI tests

- src/cmd/uds.go
- src/config/lang/lang.go
- src/pkg/bundle/deploy.go
- src/test/e2e/commands_test.go
- src/types/options.go
Adds `--retries` to deploy
Fixes #531
> feat: adds retries flag

- src/pkg/bundle/tui/deploy/handlers.go
`uds deploy k3d-core-istio-dev:0.16.1` fails 1/10 times due a race condition with the deploy ticker, this PR adds an additional check to ensure we don't seg fault
> fix: nil check pkg components in TUI

- src/cmd/uds.go
bumps retries to 3 by default to match Zarf
> fix: bumps retries to 3 by default to match Zarf

- src/test/common.go
Adds a health check to ensure registries are g2g during tests
> chore: adds registry health check for tests

- docs/overrides.md
- src/pkg/bundle/deploy.go
- src/pkg/bundle/remove.go
- src/pkg/sources/common.go
- src/pkg/sources/new.go
- src/pkg/sources/remote.go
- src/pkg/sources/tarball.go
- src/test/bundles/07-helm-overrides/namespace/uds-bundle.yaml
- src/test/e2e/bundle_test.go
- src/test/e2e/commands_test.go
- src/test/e2e/variable_test.go
- src/types/bundle.go
- uds.schema.json
enables setting namespaces in bundled Helm charts
Fixes #442
> feat: enables setting namespaces in bundled Helm charts

- main.go
- src/cmd/uds.go
- src/pkg/bundle/tui/deploy/model.go
adds global GracefulPanic and checks to deploy TUI
> fix: adds global GracefulPanic and checks to deploy TUI

- src/pkg/bundler/fetcher/fetcher.go
- src/pkg/bundler/fetcher/remote.go
- src/pkg/bundler/pusher/remote.go
- src/pkg/utils/oci.go
- src/test/bundles/13-composable-component/uds-bundle.yaml
- src/test/e2e/bundle_test.go
- src/test/packages/prometheus/images/zarf.yaml
- src/test/packages/prometheus/zarf.yaml
ensure we are pulling all Zarf pkg layers by grabbing them from the `zarf.yaml` instead of the pkg root manifest
> fix: ensure we are pulling all components

- src/pkg/bundle/common.go
- src/pkg/bundler/bundler.go
- src/pkg/bundler/localbundle.go
- src/pkg/utils/utils.go
- src/pkg/utils/utils_test.go
- src/test/e2e/bundle_test.go
- src/test/e2e/commands_test.go
Adds the ability to pass a local output path to `uds create`.
resolves #461
> feat: add ability to uds create to local output path

- README.md
- docs/overrides.md
Adds docs for the duplicate packages feature
> chore: adds dup pkgs docs

- .github/actions/k3d/action.yaml
Related to this issue: https://github.com/containerd/containerd/issues/10014
This pins the version of k3s that k3d uses, avoiding an HTTP/HTTPS issue that causes zarf init packages to fail to deploy to the cluster.
https://github.com/defenseunicorns/zarf/pull/2430
https://github.com/defenseunicorns/uds-cli/actions/runs/8623241720/job/23669501759?pr=554
https://github.com/defenseunicorns/uds-cli/actions/runs/8631062004/job/23658683639#step:6:12794
> ci: pin k3s version in k3d action to sidestep containerd issue

- README.md
> chore: refactor dev mode docs

- Makefile
- src/test/common.go
- src/test/e2e/zarf_test.go
Make sure that vendored zarf tools versions are outputted when running commands like `uds zarf tools helm version`
resolves #357
> chore: ensure vendored tools versions print out

- CONTRIBUTING.md
- src/pkg/bundle/common_test.go
- src/pkg/bundle/deploy_test.go
Updates contributing guide to add more direction on testing and how to contribute
Relates to https://github.com/defenseunicorns/uds-cli/issues/583
> chore: update contributing doc

- go.mod
Bumps Go version to 1.21.10 in light of https://nvd.nist.gov/vuln/detail/CVE-2024-24787
> chore: bump Go version to 1.21.10

- src/pkg/bundle/tui/deploy/model.go
Remove `q` for canceling deployments (too easy to accidentally kill a deployment with a single key)
> feat: remove q for canceling deploy

- README.md
- src/cmd/cmd_test.go
Testing that getArch(), which is used for calculating build info, returns the correct architecture. 
Due to complications unit testing how the config.CLIArch var gets set (via viper config loading and a cmd flag) we opted for just testing that, between CLIArch and bundle.Metadata.Architecture, CLIArch should take precedence.
...
Resolves #360
> chore: test getArch

- docs/overrides.md
- src/pkg/bundle/create.go
- src/pkg/bundle/deploy.go
- src/test/bundles/07-helm-overrides/values-file/uds-bundle.yaml
- src/test/bundles/07-helm-overrides/values-file/values.yaml
- src/test/bundles/07-helm-overrides/values-file/values2.yaml
- src/test/e2e/variable_test.go
- src/types/bundle.go
- uds.schema.json
- zarf.schema.json
Allows for passing helm overrides values from a values file.
Fixes #572
> feat: allow helm overrides from valuesfile

- adr/0005-dev-mode.md
ADR for `dev deploy` implementation
Relates to #550
> docs: dev deploy ADR

- README.md
- src/cmd/dev.go
- src/pkg/bundle/dev.go
- src/pkg/sources/common.go
- src/pkg/sources/remote.go
- src/pkg/sources/tarball.go
- src/test/e2e/commands_test.go
- src/test/e2e/dev_test.go
allows you to run `uds dev deploy` with remote bundles
Relates to #628
> feat: dev deploy remote bundles

- src/pkg/bundle/deploy.go
- src/pkg/bundle/publish.go
- src/pkg/bundle/remote.go
- src/pkg/bundle/remove.go
- src/pkg/bundle/tarball.go
- src/pkg/bundler/common.go
- src/pkg/bundler/fetcher/common.go
- src/pkg/bundler/fetcher/local.go
- src/pkg/bundler/fetcher/remote.go
- src/pkg/bundler/localbundle.go
- src/pkg/bundler/pusher/remote.go
- src/pkg/bundler/remotebundle.go
- src/pkg/sources/new.go
- src/pkg/sources/remote.go
- src/pkg/sources/tarball.go
- src/pkg/utils/boci/oci.go
- src/pkg/utils/oci.go
- src/pkg/utils/utils.go
- src/test/bundles/04-init/uds-bundle.yaml
- src/test/bundles/13-composable-component/uds-bundle.yaml
- src/test/bundles/14-optional-components/uds-bundle.yaml
- src/test/common.go
- src/test/e2e/bundle_test.go
- src/test/e2e/commands_test.go
- src/test/e2e/dev_test.go
- src/test/e2e/ghcr_test.go
- src/test/e2e/main_test.go
- src/test/e2e/optional_bundle_test.go
- src/test/packages/podinfo-and-nginx/zarf.yaml
- src/test/packages/prometheus/zarf.yaml
- ensure we only bundle images from required + selected components (results in smaller bundles)
- remove slow layer verification
https://github.com/defenseunicorns/uds-cli/issues/613
> feat: remove unnecessary bundle layers and refactor verification

- .github/workflows/release.yaml
- src/test/bundles/14-optional-components/uds-bundle.yaml
- src/test/e2e/main_test.go
- src/test/packages/podinfo-nginx/zarf.yaml
> fix: typo in Zarf pkg name and refactor smoke test workflow

- docs/runner.md
> docs: add note about UDS_ARCH

- README.md
- src/pkg/bundle/inspect.go
- src/pkg/utils/utils.go
- src/types/bundle.go
- uds.schema.json
Addresses feedback from https://github.com/defenseunicorns/uds-cli/pull/599
> chore: small refactors and docs updates

- .github/actions/save-logs/action.yaml
- .github/workflows/release.yaml
- .github/workflows/test-e2e-pr.yaml
- .goreleaser.yaml
- README.md
- docs/overrides.md
- src/cmd/uds.go
- src/config/lang/lang.go
- src/pkg/bundle/deploy.go
- src/test/bundles/07-helm-overrides/uds-bundle.yaml
- src/test/bundles/07-helm-overrides/uds-config.yaml
- tasks/tests.yaml
- clean up `lang.go`
- adds more docs for `${...}` usage https://github.com/defenseunicorns/uds-cli/issues/670
- make `test` task names shorter
- ensure we are doing PRs for brew releases
> chore: cleans up lang file and docs, use PRs for brew releases

- .github/workflows/release.yaml
- .github/workflows/test-e2e-pr.yaml
- src/test/e2e/security_hub_test.go
- tasks/tests.yaml
install trivy for security hub and parallelize release
> fix: install trivy for security hub and parallelize release

- src/pkg/utils/boci/oci.go
- src/test/bundles/14-optional-components/uds-bundle.yaml
- src/test/e2e/bundle_test.go
- src/test/e2e/optional_bundle_test.go
- src/test/packages/nginx/zarf.yaml
take docker namespace into account during deploy
Fixes https://github.com/defenseunicorns/uds-cli/issues/692
> fix: take docker namespace into account during deploy

- docs/overrides.md
Removes and extraneous quotation in the overrides docs. Noticed this because of weird syntax highlighting on https://uds.defenseunicorns.com/cli/overrides/#namespace
> docs: remove out of place quotation

- README.md
- hack/push-test-artifacts.sh
- src/test/packages/nginx/refs/zarf.yaml
- use nginx shorthand in dev deploy tests
- use `uds zarf` for push artifacts script
- (note we ran the push artifacts script to update nginx in the remote repos)
> chore: ensure nginx shorthand in dev tests

- src/cmd/monitor/pepr.go
- src/pkg/engine/pepr/stream.go
- src/pkg/engine/pepr/stream_test.go
- src/pkg/engine/stream/common.go
- src/pkg/engine/stream/common_test.go
This PR uses the native K8s timestamp feature (which is the [CRI Log format](https://github.com/kubernetes/design-proposals-archive/blob/main/node/kubelet-cri-logging.md) instead of the timestamp from the pod. This ensure behavior consistent with normal K8s log output, reduces the need to parse each timestamp and eleminates an issue that exists for timestamp parsing currently.
> fix(engine): use k8s timestamps instead of pepr timestamps

- hack/generate-schema.sh
- src/pkg/utils/utils.go
- src/test/bundles/02-variables/uds-bundle.yaml
- src/test/e2e/variable_test.go
- uds.schema.json
Print warning and fall back to non-strict unmarshalling, also update schema to allow extensions.
Fixes #719
> feat: fall back to non-strict unmarshalling

- .gitignore
- src/pkg/bundle/inspect.go
- src/test/e2e/bundle_test.go
Fixes https://github.com/defenseunicorns/uds-cli/issues/733
Noting that this is a breaking change as `--list-images` will now only go to stdout
> fix: ensure inspected image list is machine readable

- src/cmd/dev.go
- src/config/lang/lang.go
Makes `dev deploy` help messages more accurate
Fixes https://github.com/defenseunicorns/uds-cli/issues/755
> fix: make dev deploy help msg better

- .github/workflows/nightly-release.yaml
- .github/workflows/release.yaml
remove `needs` from first block of release workflows
> fix: nightly release workflow

- src/pkg/bundle/common.go
- src/pkg/bundle/remote.go
Adds additional debug messaging when validating OCI sources and attempting to resolve the root descriptor from a remote repository. 
Debug messaging now provides the resolution sequence for the remote paths that are attempted:
- provided source
- ghcr.io/defenseunicorns/packages/uds/bundles/
- ghcr.io/defenseunicorns/packages/delivery/
- ghcr.io/defenseunicorns/packages/
Fixes #705
> chore: add additional debug info on OCI source validation

- src/pkg/bundle/overrides.go
- src/test/e2e/variable_test.go
Splits envs into 2 sections explicitly, handling situations where envs have `=` in them.
Also updated the base64 secret test to include `=` since this is a common place where this could occur (base64 padding).
No issue opened, can be if required.
> fix: split override envs properly

- src/pkg/bundle/inspect.go
- src/pkg/bundle/provider.go
- src/pkg/bundle/remote.go
- src/pkg/bundle/tarball.go
- src/pkg/utils/sbom.go
- src/test/e2e/bundle_deploy_flags_test.go
- src/test/e2e/bundle_index_test.go
- src/test/e2e/bundle_test.go
- src/test/e2e/commands_test.go
- src/test/e2e/ghcr_test.go
Adding the bundle name to the bundle-sboms.tar file name for easier distinction when working with multiple bundles.
e.g. `<bundle-name>-bundle-sboms.tar`
Resolves #880
> chore: add bundle name to bundle-sbom.tar

- docs/overrides.md
- src/pkg/bundle/common.go
- src/pkg/bundle/deploy.go
- src/pkg/bundle/deploy_test.go
- src/test/bundles/07-helm-overrides/uds-bundle.yaml
- src/test/bundles/07-helm-overrides/uds-config.yaml
- src/types/bundle.go
- uds.schema.json
Adds the `Sensitive` option to bundle override variables so that sensitive variables set in a `uds-config.yaml` can be masked in deployment output.
> feat: add sensitive boolean for bundle override variables

- hack/validate-uds-core-state.sh
- src/pkg/bundle/deploy.go
- src/pkg/bundle/remove.go
- src/pkg/state/state.go
- src/test/bundles/16-state/uds-bundle.yaml
- tasks/tests.yaml
ensure cluster disconnect doesn't break deploys and removes
Adds test to UDS core smoke test nightly, proof of passing:
Fixes https://github.com/defenseunicorns/uds-cli/issues/903
> fix: ensure cluster disconnect doesn't break deploy and remove ops

- src/pkg/bundle/deploy.go
~Cleans up the positioning of `"kind:"` to be under Metadata, fixes the color output, and fixes a typo~. UPDATE: removes `"kind:"` entirely and fixes typo.
Unfortunately I couldn't merge this in with the existing `b.bundle.Metadata` struct. I tried a new inline struct that embedded the `Metadata` one but the yaml printer ended up making a new section for it, which isn't what I wanted. 
New look:
Also unfortunately, `ColorPrintYAML()` forces an empty line before printing, so that's why there's a gap there.
While I was here, I renamed the imported zarf utils package to `zarfUtils` because I noticed `uds-cli` also has a `utils` package. While we don't use the `uds-cli` one here, while experimenting here with `pterm` I found that we did and there was confusion as to which I was trying to …
> fix: cleanup color and typo

- src/config/config.go
- src/pkg/bundle/deploy.go
- src/pkg/bundle/remove.go
- src/test/e2e/bundle_deploy_flags_test.go
- tasks/tests.yaml
It was discovered during our release pipeline that the new state feature contains a bug where state could be introduced in the wrong cluster. This PR wraps all state-related code in feature flag so we can release
> feat: adds feature flag to state

- src/cmd/common.go
Remove extra Zarf logging output. Previously, we saw an extra note from Zarf saying where a log file was located, this PR removes that behavior by disabling `pterm` output briefly while setting up the Zarf CLI
Noting that the Zarf output pointed to a log file with no useful information because we capture all the useful output in the UDS log file
> fix: remove extra Zarf logging output

- renovate.json
Renovate seems to be broken at the moment. In this PR we try to fix it. Pray I do not try to fix it further
> fix: update renovate to hopefully fix uds-runtime dep

- .github/actions/golang/action.yaml
- .github/actions/k3d/action.yaml
- .github/actions/setup-from-previous/action.yaml
- .github/workflows/nightly-uds-core.yaml
- .github/workflows/release-tests.yaml
- .github/workflows/test-e2e-pr.yaml
Cleanup some of our GitHub Actions, and run (some of?) our e2e tests in a matrix where one scenario we have k3d installed and a cluster created, and another with k3d installed and no cluster created.
**Note about our `setup-golang` action:** I noticed that we were using `setup-go` to install go `1.21.x`, however the `setup-go` action does not list the `.x` syntax as supported. Furthermore our `go.mod` file says go 1.22.4, so the setup go action was setting 1.21.x, and then immediately switching to go 1.22.4 because that's what our go.mod says. The result was a long list of errors trying to use 1.22 because it was being pulled from cache but conflicted with the 1.21 we just setup. 
See here for example: https://github.com/defenseunicorns/uds-cli/actions/runs/11037302233/job/30657907519#step …
> chore: matrix testing pre-existing k3d clusters

- .github/workflows/release-tests.yaml
The nightly CI release workflow has been busted since we added matrix testing due to conflicts in the log names. This PR adds a suffix for the matrix type to distinguish.
> fix: add suffix to smoke test logs

- .github/actions/install-tools/action.yaml
- .github/workflows/release.yaml
- .grype.yaml
Reverts defenseunicorns/uds-cli#961
It turns out these tools are used in the release process, albeit in a sort of hidden way (to me at least), by goreleaser.
> fix: revert "fix: remove unused GitHub Action install-tools"

- .golangci.yml
- .pre-commit-config.yaml
Sometimes, for _reasons_, the `pre-commit` linting check will fail because the `golangci-lint` step takes over [5 minutes in CI](https://github.com/defenseunicorns/uds-cli/actions/runs/12378236202/job/34549623374?pr=1043#step:6:106), where as other times [it finishes just shy of 5 minutes](https://github.com/defenseunicorns/uds-cli/actions/runs/12378278826/job/34549772864?pr=1029#step:6:106). 
In this PR we take an unscientific approach to fixing this by just giving it more time and bump the limit up 6 minutes.
> chore: give golangci-lint an extra minute to complete

- go.mod
- go.sum
- src/pkg/tfparser/parser.go
- src/pkg/tfparser/parser_test.go
Adds a package `tfparse` for parsing `*.tf` files specifically for our usage in bundle creation. Right now we only parse out the required parts. 
Note: this PR is opened against the `uds-tofu` branch
> feat: add tfparse package for parsing terraform files

- .github/workflows/scan-lint.yaml
- .gitignore
- src/cmd/internal.go
- src/cmd/vendored.go
- src/config/lang/lang.go
- tasks.yaml
- tasks/docs.yaml
- tasks/schema.yaml
- tasks/tests.yaml
Working towards embedding the `tofu` binary within the UDS CLI. This embedded binary currently only exposes the `tofu plan (uds plan)` and `tofu apply (uds apply)` subcommands.
TODO: 
1. `tofu` is somewhere on your path
2. You are ONLY building the UDS CLI for your specific arch (since it is ONLY using the already existing tofu for your arch)
> chore: embed tofu binary and expose 'plan' and 'apply'

- src/pkg/tfparser/parser.go
- src/pkg/tfparser/parser_test.go
This PR adds to the `tfparser` to extract the bundle metadata from the `uds_bundle_metadata` resource, defined like so:
```hcl
resource "uds_bundle_metadata" "basic" {
kind        = "UDSBundle"
version     = "0.1.0"
description = "This is a basic bundle"
}
```
NOTE: also fix an issue where the parser would panic if something it thought was required was missing (ex `version` in the `required_providers` block)
> feat: parse uds_bundle_metadata resource

- docs/reference/CLI/commands/uds_dev_tofu-create.md
- src/cmd/common.go
- src/cmd/dev.go
- src/config/config.go
- src/pkg/bundle/create.go
- src/pkg/bundler/bundler.go
- src/pkg/bundler/localbundle.go
- src/types/options.go
Parses `uds-bundle.tf` files and generates a `uds-bundle-fake-metadata-0.0.0.tar.zst` tarball bundle.
There is (a lot) more work that will need to be implemented to ensure full feature parity with the standard `uds create` from a `uds-bundle.yaml` file, but I believe this PR offers a good starting point.
The changes in this PR add additional config booleans to check against so we do not change the behavior of a standard `uds create` command.
😰😬🙈
> feat: add 'dev tofu-create' command to build bundles from a uds-bundle.tf config

- docs/reference/CLI/commands/uds_dev_extract.md
- src/cmd/dev.go
- src/pkg/bundle/common.go
- src/pkg/bundle/deploy.go
Bundles created from a `uds-bundle.tf` source file store the SHA256 checksum of the Zarf Package manifest in different place than bundles created from a `uds-bundle.yaml`
😰😬🙈
> chore: update 'dev extract' command to work with bundles built from a uds-bundle.tf source

- docs/reference/CLI/commands/uds_dev_tofu-deploy.md
- src/cmd/common.go
- src/cmd/dev.go
- src/pkg/bundle/common.go
- src/pkg/bundle/create.go
- src/pkg/bundle/deploy.go
- src/pkg/bundle/dev.go
- src/pkg/tfparser/parser.go
- src/pkg/tfparser/parser_test.go
- src/types/options.go
Extract zarf packages from the bundle and provides the necessary flags to tofu to deploy the packages and save state locally.
😰😬🙈
> feat: add scaffolding for deploying bundles built from a .tf source

- renovate.json
This PR focuses on improving the experience with Renovate PRs. There are a few particular changes of note:
- Removing limits and schedule on renovate PRs: This allows PRs to be created quickly and as many as needed. Happy to re-add the schedule if that is the desire of the team.
- Updating the package rules to group dependencies into a few discrete buckets:
- Github actions/workflows: anything under `.github`
- Test dependencies: anything under `src/test` and `tasks`
- Go dependencies: anything in `go.sum` and `go.mod` except zarf
- Zarf: any zarf updates (regardless of file)
Based on a skim of the repo I think this covers all renovate updates, but these categories can be updated or expanded as needed. I validated this [on my repo](https://github.com/mjnagel/uds-cli/pulls) for an example …
> chore: regroup and unlimit renovate

- .github/actions/save-logs/action.yaml
- .github/workflows/nightly-ghcr.yaml
- .github/workflows/parallel-tests.yaml
- .github/workflows/release-tests.yaml
- .github/workflows/test-schema-and-docs.yaml
- .github/workflows/test-unit.yaml
Replaces our dependency on uds-common save-logs GitHub action that was removed a long time ago. 
Closes https://github.com/defenseunicorns/uds-cli/pull/1074
Relates to #
> chore: copy over our own save-logs

- tasks.yaml
Without setting these buildflags, some `uds zarf` commands could produce different results than directly using `zarf` of the same version. See details for example.
<details>
```
❯ uds version               
v0.20.0
❯ uds zarf version                    
v0.45.0
❯ zarf version                    
v0.45.0
❯ uds zarf dev find-images -f upstream
[... omitted things ...]
NOTE  Using build directory .
[... omitted things ...]
ERROR:  unable to find images: could not render the Helm template for [some chart]: error
generating helm chart template: chart requires kubeVersion: >=1.24.0-0 which is incompatible with
Kubernetes v1.20.0
❯ zarf dev find-images -f upstream    
[... omitted things ...]
NOTE  Using build directory .
[... omitted things ...]
components:
- name: [some chart]
images:
- alpine …
```
> chore: set helm buildflags the way Zarf does

- .github/workflows/scan-lint.yaml
- .pre-commit-config.yaml
- docs/reference/CLI/commands/uds_publish.md
- docs/reference/CLI/quickstart-and-usage.md
- src/cmd/uds.go
- src/config/lang/lang.go
- src/test/e2e/bundle_test.go
Deprecate the `--version` flag on the `publish` command, since it doesn't work as it was thought to. 
Also updates the `golangci-lint` version used in pre-commit, since it was failing for error code `-9` _for reasons_ but passes fine with an updated version.
- related to #1008
> chore: add deprecation warning to publish --version

- src/cmd/common.go
- src/pkg/bundle/common.go
- src/pkg/bundle/dev.go
- src/pkg/bundler/fetcher/common.go
- src/pkg/bundler/fetcher/fetcher.go
- src/pkg/bundler/fetcher/local.go
- src/pkg/bundler/fetcher/remote.go
- src/pkg/bundler/localbundle.go
- src/pkg/bundler/remotebundle.go
- src/test/e2e/optional_bundle_test.go
fixes issue where bundles that referenced a Signed Zarf Package on the local filesystem were unable to be built
**NOTE:**
I think this should be considered (and advertised) as a breaking change. Bundles that were utilizing signed Zarf Packages without providing the publickey are now going to give an error when being created instead of silently failing/continuing before.
> fix!: use provided public signing key to build bundles with local signed zarf packages

- renovate.json
pterm v0.12.80 breaks our things. Let's remove it from renovate so our other deps can be updated. This should exclude just the single broken version
> chore: update renovate to exclude pterm v0.12.80

- src/cmd/common.go
- src/pkg/bundle/common.go
- src/pkg/bundle/dev.go
- src/pkg/bundler/fetcher/common.go
- src/pkg/bundler/fetcher/fetcher.go
- src/pkg/bundler/fetcher/local.go
- src/pkg/bundler/fetcher/remote.go
- src/pkg/bundler/localbundle.go
- src/pkg/bundler/remotebundle.go
- src/test/e2e/optional_bundle_test.go
This reverts commit cbcf3daf300281a3451654c4fba5683213283c70.
Revert this commit because this ended up breaking the layer cache when building bundles. The layer cache broke because instead of UDS-CLI using custom internal logic to pull the zarf layers, UDS-CLI utilized the Zarf SDK to pull the entire package down. This change wasn't detected with our current testing suite.
I believe we can (and should) be using Zarf to pull packages (vs using custom logic within the UDS-CLI repo to perform pulls) but we should ensure that we are managing the cache of images layers correctly when we implement that approach. When that time comes, I believe we would be able to 'simply' utilize the Zarf Cache.
Fixes #
Relates to #
> Revert "fix!: use provided public signing key to build bundles with signed zarf packages

- .goreleaser.yaml
Setting `ignore_tags` in the `.goreleaser.yaml` file should allow us to ignore the `nightly` tag when creating the Changelog release notes. 
I copied these values from this documentation page: 
- https://goreleaser.com/customization/git/?h=ignore_tags
Fixes #911
> chore: set ignore_tag properties in goreleaser

- .goreleaser.yaml
https://github.com/defenseunicorns/uds-cli/pull/1124 introduced `ignore_tags` to our `.goreleaser.yaml` file, with the idea of ignoring certain tags when creating the changelog. Unfortunately using the `"{{.Env.IGNORE_TAG}}"` template option results in an error if the `IGNORE_TAG` environment variable doesn't exist. 
In this PR I remove that, as well as clean up other parts of the file after running `goreleaser check` on the file (ex. `format` and `version_template` options are deprecated).
> fix: updates to .goreleaser.yaml

- CODEOWNERS
Adds the `@defenseunicorns/uds-experience` as an owner of the repo, enabling that team to maintain the project.
> chore: add uds-experience as codeowners

- src/pkg/bundle/publish.go
- src/pkg/bundle/tarball.go
- src/pkg/utils/utils.go
use open and stream data vs reading all the data into memory
Seeing max resident set size of 131.25 MB when publishing core demo which is comparable to the RSS previously.
Fixes #1128
Summary:Publishing bundles using uds-cli versions greater than v0.22.0 causes a significant increase in memory usage compared to earlier versions. For a basic k3d-core-demo bundle, the peak memory usage jumps from ~136 MB in v0.21.0 to over 4.6 GB in v0.25.0. For larger bundles, usage climbs as high as 25 GB, making publishing impossible on standard CI runners.
> chore: decrease ram usage

- tasks/tests.yaml
Latest k3d-core-slim-dev adds another gateway resource, so the smoke test status checks need to be updated with the fully qualified resource name. ```gateways.networking.istio.io```
> chore: update gateway resource to check in latest slim-dev bundle

- src/pkg/bundle/common.go
- src/pkg/bundle/deploy.go
- src/pkg/sources/new.go
- src/pkg/sources/remote.go
- src/pkg/sources/tarball.go
Bug fix where the public key was not correctly getting passed down to the zarf package deploy step
Fixes #1211
> fix: update options to include public key info
