.github/workflows/scan-codeql.yml
src/config/lang/lang.go
src/pkg/bundler/bundle.go
src/pkg/bundler/create.go
src/pkg/bundler/remote.go
src/test/bundle_test.go

Adding capability to create a UDS Bundle and output it locally instead of in an OCI registry

Output UDS Bundles to local filesystem

---

adr/0001-bundle-schema-tooling.md

adds schema tooling ADR

---

.github/actions/zarf/action.yaml
README.md
src/pkg/bundler/deploy.go
src/test/e2e/bundle_test.go
src/test/packages/01-uds-bundle/uds-bundle.yaml

bumps Zarf version

---

.github/workflows/release.yaml
.goreleaser.yaml

Sets up `goreleaser` for automated releases

adds release workflow to CI

---

src/pkg/bundle/common.go

Removing because this feature is not used and doesn't fit the declarative nature of Bundle configuration

Remove wildcard components feature

---

README.md
src/cmd/bundle.go
src/pkg/bundle/bundle.go
src/pkg/bundle/provider.go
src/pkg/bundle/publish.go
src/pkg/bundle/remote.go
src/pkg/bundle/tarball.go
src/pkg/bundler/remote.go
src/pkg/bundler/tarball.go
src/test/e2e/bundle_test.go
src/types/bundler.go

- Adds publish cmd to allow publishing local bundles
- Fixes some bugs/discrepancies between local and remote bundles

adds publish cmd

---

src/pkg/bundle/remove.go

- Removes bundled Zarf pkgs from the bottom up (ie. reverse order)

reverses remove order

---

src/pkg/bundle/deploy.go
src/pkg/bundle/remote.go
src/pkg/bundle/tarball.go

This fixes the deploy from GHCR bug. Testing is weird with GHCR login, going to tackle that in a follow-up PR to get SWF ready for demo

Fixes bug when deploying from GHCR

---

README.md

- updates UDS CLI docs to remove `bundle` keyword

updates docs

---

README.md
src/cmd/deprecated_bundle.go
src/cmd/uds.go
src/config/lang/lang.go
src/pkg/bundle/create.go
src/pkg/utils/utils.go
src/test/e2e/bundle_test.go
src/test/packages/01-uds-bundle/uds-bundle.yaml
src/test/packages/03-local-and-remote/uds-bundle.yaml
src/test/packages/04-local-init/uds-bundle.yaml

- removes bundle templating feature to make `uds-bundle.yaml` more declarative

removes bundle templating

---

src/pkg/bundle/bundle.go

- removes some more "bundle" syntax references

removes more bundle verbiage

---

src/pkg/bundle/bundle.go
src/pkg/bundle/common.go
src/pkg/bundle/create.go
src/pkg/bundle/deploy.go
src/pkg/bundle/remote.go
src/pkg/bundler/remote.go

closes #29 #28 
co-author @Michael-Kruggel

More, Better, and Fixed Progress Indicators

---

CODEOWNERS

adds decleaver to codeowners

---

hack/generate-schema.sh
hack/test-generate-schema.sh
src/cmd/internal.go
src/cmd/run.go
src/config/config.go
src/config/lang/lang.go
src/pkg/runner/runner.go
src/test/common.go
src/test/e2e/main_test.go
src/test/e2e/runner_test.go
src/test/tasks.yaml
src/types/tasks.go
tasks.schema.json

Adds a `uds run` cmd to run an `tasks.yaml` that define reusable workflows. Needs docs, following up with this ticket: https://github.com/defenseunicorns/uds-cli/issues/141

adds uds run command

---

src/pkg/runner/runner.go

feat: add UDS/Zarf arch env variable to runner

---

README.md
docs/runner.md
src/pkg/runner/runner.go
src/pkg/utils/oci.go
src/test/common.go
src/test/e2e/runner_test.go
src/test/tasks/remote-import-tasks.yaml
src/test/tasks/tasks.yaml

Allows users to import remote tasks in the UDS runner

feat: import remote tasks into runner

---

.github/workflows/release.yaml

Fixes bug in release CI where an e2e test was unable to access GHCR

fix: updates release CI to write to GHCR for e2e tests

---

.github/actions/zarf/action.yaml
.gitignore
renovate.json
src/test/bundles/04-init/uds-bundle.yaml
src/test/e2e/main_test.go

Updates Renovate config to automate Zarf updates in `uds-bundle.yaml` files and a GA `action.yaml`
Fixes #110

chore: automate Zarf upgrades in code

---

src/cmd/uds.go
src/config/lang/lang.go
src/pkg/bundle/remove.go
src/test/e2e/bundle_test.go
src/types/bundler.go

Adding --packages flag to remove command to allow users to specify which zarf packages they want removed.
Addresses #234

feat: adds packages flag for remove

---

src/types/bundle.go
uds.schema.json

chore: update uds-bundle.yaml schema docs

---

README.md

Add documentation for --packages flag for deploy and remove commands
Relates to #237

chore: add --packages documentation

---

README.md
docs/overrides.md
src/cmd/uds.go
src/pkg/bundle/deploy.go
src/test/bundles/02-simple-vars/uds-bundle.yaml
src/test/bundles/07-helm-overrides/uds-bundle.yaml
src/test/bundles/07-helm-overrides/uds-config.yaml
src/test/e2e/bundle_test.go
src/test/packages/helm/unicorn-podinfo/values.yaml
src/test/packages/helm/zarf.yaml
src/types/bundler.go

Enables complex overrides for bundle helm variables
Fixes #244

feat: enable complex overrides for bundle helm variables

---

README.md
docs/overrides.md
src/cmd/uds.go
src/cmd/viper.go
src/pkg/bundle/bundle.go
src/pkg/bundle/common.go
src/pkg/bundle/common_test.go
src/pkg/bundle/deploy.go
src/pkg/bundle/remote.go
src/pkg/bundle/remove.go
src/pkg/bundler/remote.go
src/test/bundles/01-uds-bundle/uds-bundle.yaml
src/test/bundles/02-simple-vars/uds-bundle.yaml
src/test/bundles/02-simple-vars/uds-config.yaml
src/test/bundles/03-local-and-remote/uds-bundle.yaml
src/test/bundles/04-init/uds-bundle.yaml
src/test/bundles/05-gitrepo/uds-bundle.yaml
src/test/bundles/06-ghcr/uds-bundle.yaml
src/test/bundles/07-helm-overrides/uds-bundle.yaml
src/test/bundles/07-helm-overrides/uds-config.yaml
src/test/e2e/bundle_test.go
src/types/bundle.go
src/types/bundler.go
uds.schema.json

- Refactors `uds-bundle.yaml` from `zarf-packages` -> `packages
- Refactors `uds-config.yaml` as described in #223 
- Ensures vars in `uds-config.yaml` can be upper or lowercase
#223 
#249

refactor: simplifies bundle and config schema

---

README.md

- Adds docs on how to share the same variable between multiple packages with minimal syntax
- Adds more docs + examples on UDS first class things

docs: shared vars + first class UDS

---

README.md
docs/anatomy.md
docs/runner.md

chore: cleans up docs

---

.github/workflows/test-e2e.yaml
Makefile
README.md
go.mod
go.sum
src/cmd/root.go
src/cmd/uds.go
src/pkg/bundle/deploy.go
src/test/common.go
src/test/e2e/bundle_test.go
src/test/e2e/commands_test.go
src/test/e2e/main_test.go
src/test/e2e/variable_test.go

Vendors Zarf inside of UDS CLI to remove UDS's dependency on a system Zarf
Fixes #167

feat: vendors Zarf inside of UDS CLI

---

main.go
src/pkg/bundle/common.go
src/pkg/bundle/common_test.go

[Add Validation to Bundle Overrides](https://github.com/defenseunicorns/uds-cli/issues/209)
Fixes #209

feat: add validation to bundle overrides

---

.goreleaser.yaml
docs/runner.md

- Adds a build flag to the goreleaser
- Adds a note in the runner docs about `--list`

chore: updates goreleaser and adds runner doc

---

src/cmd/uds.go
src/config/config.go
src/pkg/bundle/create.go
src/test/bundles/09-uds-bundle-yml/uds-bundle.yml
src/test/bundles/09-uds-bundle-yml/uds-config.yml
src/test/e2e/bundle_test.go
src/types/bundler.go

Updated to handle both uds-bundle.yaml and uds-bundle.yml
Fixes https://github.com/defenseunicorns/uds-cli/issues/268

feat: handle bundle yaml and yml files

---

renovate.json
src/test/packages/helm/unicorn-podinfo/Chart.lock
src/test/packages/helm/unicorn-podinfo/Chart.yaml
src/test/packages/helm/zarf.yaml

- updates podinfo
- updates renovate config

chore: update podinfo

---

.github/pull_request_template.md
src/cmd/root.go

fix: uds arg check

---

src/pkg/bundle/provider.go
src/pkg/bundle/tarball.go

Removes code related to pulling local bundles 🤷

chore: removes dead code related to pulling local bundles

---

README.md
hack/push-test-artifacts.sh
src/cmd/root.go
src/config/config.go
src/pkg/bundle/bundle.go
src/pkg/bundle/create.go
src/pkg/bundle/deploy.go
src/pkg/bundle/publish.go
src/pkg/bundle/pull.go
src/pkg/bundle/remote.go
src/pkg/bundle/remove.go
src/pkg/bundle/tarball.go
src/pkg/utils/oci.go
src/test/bundles/11-real-simple/uds-bundle.yaml
src/test/e2e/bundle_test.go
src/test/e2e/commands_test.go
src/test/e2e/ghcr_test.go
src/test/e2e/variable_test.go
src/test/packages/no-cluster/real-simple/zarf.yaml

- Enables multi-arch bundles
- Remove bundle tag restrictions
- Lots of refactoring

feat: support multi-arch, refactor ref

---

src/pkg/bundle/deploy.go

There seems to be an excessive number of copy operations for variables being placed into the package variable map in the bundler's loadVariables function. 
This PR addresses ^
Fixes #344

chore: clean up load variables function

---

README.md
adr/0002-runner.md
docs/runner.md

Adds docs related to the DD project with adds the `with` and `inputs` syntax among other features

chore: adds more runner docs

---

src/cmd/viper.go
src/pkg/bundle/create.go
src/test/e2e/bundle_test.go
src/test/e2e/commands_test.go

fix: honors UDS_ env vars

---

CODEOWNERS
hack/generate-schema.sh
zarf.schema.json

- Adds Zarf schema to this repo using the version of Zarf that is vendored in UDS CLI
Fixes #416

feat: adds Zarf schema for version of Zarf used in UDS CLI

---

src/cmd/root.go
src/cmd/uds.go
src/pkg/bundle/common.go
src/pkg/bundle/create.go
src/pkg/bundler/bundler.go
src/pkg/bundler/fetcher/local.go
src/pkg/bundler/fetcher/remote.go
src/pkg/bundler/localbundle.go
src/pkg/bundler/pusher/remote.go
src/pkg/runner/runner.go
src/test/bundles/03-local-and-remote/uds-bundle.yaml
src/test/bundles/04-init/uds-bundle.yaml
src/test/bundles/05-gitrepo/uds-bundle.yaml
src/test/bundles/07-helm-overrides/uds-bundle.yaml
src/test/bundles/08-var-precedence/uds-bundle.yaml
src/test/bundles/09-uds-bundle-yml/uds-bundle.yml
src/test/bundles/11-real-simple/uds-bundle.yaml
src/test/e2e/bundle_test.go

This PR fixes --tmpDir being ignored on create 
Fixes #430

fix: use tmpdir if provided

---

src/pkg/sources/tarball.go

- fixes https://github.com/defenseunicorns/uds-cli/issues/438
Fixes #
Relates to #

fix: path traversal bug

---

.github/workflows/nightly-uds-core.yaml

Adds k3d to smoke test for UDS Core

fix: adds k3d to smoke test

---

docs/runner.md

fix: typo in docs

---

.github/workflows/release.yaml

swap release workflow to GH app

chore: swap release workflow to GH app

---

src/pkg/bundle/dev.go

- ensure we can use absolute paths in `dev deploy`

fix: ensure we handle paths correctly in dev deploy

---

src/pkg/bundler/fetcher/remote.go

removes dead code identified in https://github.com/defenseunicorns/uds-cli/pull/581

chore: remove dead end code

---

CONTRIBUTING.md
README.md
docs/overrides.md
src/test/bundles/08-var-precedence/uds-config.yaml

Fixed various grammatical typos I came across.
Fixes #
Grammatical Typos

chore: fix typos

---

.github/workflows/release.yaml
.github/workflows/test-e2e-pr.yaml

fix: release workflow typos

---

ui/src/lib/components/SideNav/SideNavMenu.svelte
ui/src/routes/(platform)/dashboard/+layout@(platform).svelte

Re-factoring the side nav to DRY up the code
Fixes #
Relates to #

Refactoring the side nav

---

docs/overrides.md

chore: fix valuesFiles examples

---

docs/bundle-anatomy.md

Fixed spelling of bundle
...
Fixes #
Relates to #

fix: update bundle-anatomy.md

---

CONTRIBUTING.md
adr/0008-cli-output.md
src/cmd/monitor/pepr.go
src/pkg/bundle/inspect.go
src/test/e2e/bundle_test.go
src/test/e2e/monitor_test.go

- adds ADR for distinguishing between stdout and stderr and implements
Fixes https://github.com/defenseunicorns/uds-cli/issues/722

feat: distinguish between stdout and stderr output

---

ui/src/routes/(platform)/monitor/pepr/pepr.test.ts
ui/src/routes/+page.svelte

Updating welcome page and fixing monitor pepr tests
Fixes #
https://github.com/defenseunicorns/uds-cli/issues/728
Re-factor

Update welcome page

---

.github/workflows/release.yaml

Fixes the following typos identified by the release pipeline

fix: release pipeline

---

.github/workflows/release.yaml

fix: release pipeline again

---

.github/workflows/nightly-ghcr.yaml
.github/workflows/parallel-tests.yaml
.github/workflows/release.yaml
.github/workflows/test-unit.yaml
docs/runner.md
src/cmd/vendored.go
src/pkg/bundle/deploy.go
src/pkg/bundle/inspect.go
src/pkg/bundle/publish.go
src/pkg/bundle/pull.go
src/pkg/bundle/remote.go
src/pkg/bundle/remove.go
src/pkg/bundle/tarball.go
src/test/e2e/runner_test.go

make runner output prettier in CI
Fixes https://github.com/defenseunicorns/uds-cli/issues/749 https://github.com/defenseunicorns/uds-cli/issues/529

feat: make runner output prettier in CI

---

src/pkg/bundle/deploy.go
src/pkg/bundle/deploy_test.go
src/pkg/bundle/overrides.go

Refactoring overrides to make code more readable and maintainable.
Relates to #654

chore: refactor overrides

---

hack/generate-docs.sh
src/pkg/bundle/deploy_test.go

fix: failing unit test due to NO_PROGRESS env var

fix: failing unit test due to NO_PROGRESS env var

---

.github/workflows/parallel-tests.yaml
docs/command-reference/uds_completion.md
docs/schema-validation.md
src/cmd/completion.go
src/cmd/internal.go
src/cmd/root.go
src/config/lang/lang.go
src/test/e2e/completion_test.go
tasks/tests.yaml

Fix links, fix schema page title, remove powershell refs
Fixes #793

fix: cli docs

---

.github/workflows/nightly-release.yaml
.github/workflows/parallel-tests.yaml
.github/workflows/release-tests.yaml
.github/workflows/release.yaml
.github/workflows/test-e2e-pr.yaml
.goreleaser-nightly.yaml

feat: nightly releases

---

.github/workflows/nightly-release.yaml
.github/workflows/test-e2e-pr.yaml

fix: nightly workflow fix

---

.github/workflows/nightly-release.yaml
.github/workflows/release.yaml

fix: permissions in nightly release

---

.github/workflows/nightly-release.yaml
.github/workflows/release-tests.yaml
.github/workflows/release.yaml

fix: fix nightly again

---

.github/workflows/nightly-release.yaml
.github/workflows/release.yaml

fix: inherit write perms for release workflow

---

.github/workflows/nightly-release.yaml
.github/workflows/release.yaml

fix: nightly release perms again

---

.github/workflows/nightly-release.yaml
.github/workflows/test-e2e-pr.yaml
hack/create-nightly-tag.sh

Commenting out tests in nightly workflow to test the inline github script

fix: test github script in release workflow

---

.github/workflows/nightly-release.yaml

fix: fast feedback for nightly script

---

.github/workflows/nightly-release.yaml

fix: add env var to nightly script

---

.github/workflows/nightly-release.yaml

fix: checkout repo after tagging

---

.github/workflows/nightly-release.yaml
.goreleaser-nightly.yaml

fix: goreleaser skip validate on nightly

---

.github/workflows/nightly-release.yaml
hack/create-nightly-tag.sh

fix: add semver to nightly

---

.github/workflows/nightly-release.yaml
hack/create-nightly-tag.sh

chore: nightly releases

---

docs/runner.md
src/test/bundles/04-init/uds-bundle.yaml
src/test/bundles/14-optional-components/uds-bundle.yaml
src/test/common.go

Update Zarf references to new repo

chore: update zarf references to new repo

---

go.mod
go.sum
renovate.json
src/test/bundles/04-init/uds-bundle.yaml
src/test/bundles/14-optional-components/uds-bundle.yaml

chore: updates Zarf to 0.36.1

---

.github/workflows/nightly-release.yaml
tasks.yaml

nightly release typo and add checksums
Fixes https://github.com/defenseunicorns/uds-cli/issues/827

fix: nightly release typo and add checksums

---

src/cmd/common.go
src/cmd/common_test.go
src/cmd/dev_test.go
tasks/tests.yaml

Fixes the invalid config option error received when trying to use the oci_concurrency option.
Fixes #840

fix: error on oci_concurrency

---

docs/quickstart-and-usage.md
src/config/config.go
src/pkg/bundle/deploy.go
src/pkg/bundle/deploy_test.go
src/test/bundles/04-init/uds-config.yaml

enables users to configure `zarf init` options
Fixes https://github.com/defenseunicorns/uds-cli/issues/839

feat: handle external registry with zarf init opts

---

CODEOWNERS

Based on current ownership of CLI, removing myself!

chore: remove mjnagel from codeowners

---

.github/workflows/release.yaml

free up disk space on release workflow
using suggestion from https://github.com/orgs/community/discussions/25678

fix: free up disk space on release workflow

---

CODEOWNERS

Adding myself to the codeowners file

chore: add catsby to CODEOWNERS

---

.gitignore
src/pkg/bundle/remote.go
src/pkg/bundle/tarball.go
src/pkg/utils/sbom.go
src/test/e2e/bundle_deploy_flags_test.go
src/test/e2e/bundle_test.go
src/test/e2e/commands_test.go
src/test/e2e/ghcr_test.go

- Fixes GHCR tests
- Ensures extracted SBOM dir reflects bundle name

fix: ghcr tests and extracted sbom naming

---

docs/command-reference/uds_publish.md
docs/quickstart-and-usage.md
src/cmd/uds.go
src/config/lang/lang.go
src/pkg/bundle/publish.go
src/pkg/bundle/tarball.go
src/test/e2e/bundle_test.go
src/types/options.go

Allow users to specify a custom tag when publishing bundles.
Resolves #888

feat: allow custom tags when publishing bundles

---

.github/actions/k3d/action.yaml
.github/workflows/nightly-uds-core.yaml

Use k3d action for setting up nightly uds core smoke tests

fix: updates nightly uds core smoke test again

---

.gitignore
docs/design/bundle-state.md

Before we too much further on the implementation of UDS state, let's take a step back and formally decide on some implementation details

chore: updates uds state design doc

---

src/pkg/bundle/deploy.go
src/pkg/bundle/remove.go
src/pkg/state/state.go
src/test/e2e/state_test.go

Updates state to match design doc

feat: updates state to match design doc

---

design-docs/0001-bundle-state.md
docs/command-reference/uds_deploy.md
docs/command-reference/uds_dev_deploy.md
docs/quickstart-and-usage.md
src/cmd/dev.go
src/cmd/uds.go
src/config/lang/lang.go
src/pkg/bundle/deploy.go
src/pkg/bundle/inspect.go
src/pkg/bundle/prune.go
src/pkg/bundle/remove.go
src/pkg/sources/new.go
src/pkg/sources/zarf-state.go
src/pkg/state/state.go
src/test/bundles/16-state/prune/uds-bundle.yaml
src/test/bundles/16-state/prune/updated/uds-bundle.yaml
src/test/bundles/16-state/updated/uds-bundle.yaml
src/test/bundles/16-state/updated/updated-again/uds-bundle.yaml
src/test/e2e/state_test.go
src/types/options.go

- adds prune flag for removing orphaned packages
- updates state design doc
https://github.com/defenseunicorns/uds-cli/issues/614

feat: adds prune flag for removing unreferenced packages

---

.github/actions/k3d/action.yaml
.github/workflows/nightly-uds-core.yaml

ensure we aren't creating a cluster for the uds-core smoke test

fix: ensure we aren't creating a cluster for the uds-core smoke test

---

tasks/tests.yaml

remove uds core nightly state checks for now

fix: remove uds core nightly state checks for now

---

src/cmd/ui.go
src/test/e2e/ui_test.go
tasks/tests.yaml

- ensures bin cleanup on `uds ui`
- updates tests and ensures tests are run in CI

fix: ensures bin cleanup on uds ui

---

.github/workflows/release.yaml

ensure runtime bins are included in releases

fix: ensure runtime bins are included in releases

---

.github/workflows/parallel-tests.yaml

Hoping to fix CI... a specific test is failing which I can't reproduce locally, but CI is giving error messages about node versions.

fix: setup specific node js version

---

.github/workflows/scorecard.yaml

Remove the usage of the very likely expired secret token that also might not actually be needed

fix: remove scorecard token

---

go.mod
go.sum
src/cmd/ui.go

Updates to UDS-Runtime v0.7.0. A manual PR b/c a package was moved around and I guess Renovate/go.mod couldn't sort that out

chore(deps): update to uds-runtime v0.7.0

---

CONTRIBUTING.md
README.md
docs/quickstart-and-usage.md

chore(docs): update links

---

docs/reference/CLI/schema-validation.md

fix: schema validation link

---

renovate.json

An attempt to batch/group our Renovate updates, so that all GitHub Actions updates are bundled together to reduce PR noise

chore: batch renovate actions

---

renovate.json

Another attempt to batch/group the renovate updates

chore: more renovate cleanup

---

go.mod
go.sum
hack/generate-schema.sh
src/test/bundles/04-init/uds-bundle.yaml
src/test/bundles/14-optional-components/uds-bundle.yaml

chore: update zarf to v0.53.0

---

src/pkg/bundle/deploy.go
src/pkg/message/connect.go
tasks/tests.yaml

Prints the connect table for deployed components, unless the package is init config.
...
Fixes #1210 
Relates to #

fix(deploy): print connect table on deploy

---

docs/reference/CLI/quickstart-and-usage.md

fix broken link to bundle override docs

chore(docs): fix broken link to bundle override docs

---

.github/workflows/nightly-integration-test.yaml
.github/workflows/parallel-tests.yaml

Quick nightly workflow for testing the integration of zarf@main. 
Could use a team notification workflow - such as `create-or-update-comment` action but this PR is simply for some quick feedback. 
No related issue yet

chore(test): add zarf@main integration test nightly

---

src/pkg/bundle/overrides.go

chore: remove suffix mutation for templated variables

---

src/pkg/utils/utils.go

fix: create missing output dir before permission check
